language: rust
rust:
- stable
- beta
- nightly
sudo: false
os:
- linux
cache:
  directories:
  - "$HOME/.cargo"
  - target
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
env:
  matrix:
  - CARGO_FEATURES=
  global:
  - secure: HKjJNlircbxNwT51F47JiAH1ruxJOA5veOlmycSod6AR6If09eIu7lQLeRnHaAcys12ccJ9sUq9Z50fPVI3Bc7PVM2cNIWnybTM0jhOLHe9hd5M1YS+4p4qlgTiWBUxVveqVmy9OXbPN8esH9VempJy1pV68YgijkaL8OnM8MPZGMEuZbYF7+5pdWTHSO/h2twXWK5SYGqTLwxM+NJMIOmRznjmi0aI0Kfp1GiHEFKMGEvaLjeaIu71rAmC6kSRohoPPfXzuJbBPx58aBSNvdl4KA8nyJtsLynjMNO0nxzzgdXnkoBXu9EuuMppu/k6rqcAKFpDX98sFU1EzXoSdPr7gWMi9T3c2Dk85kTJX+uVUxndkICQMVENFFyC5sRQFopSPsVl3xyePHJI7c/v0H/OuYvJH7K/0QOuquclZQMPBIoFXtA7cxLvv+w/6innE3ABgUE9Xt30dbRD2XkCPJfoyhmARSt0TXXl/JhCNwQWfG9LRQvshKL4mzOaEV0YjVsGXfs/IaMUrmKOA3pDyeSU8ufG8MBIUpcl17SCAFn1m8oJcRiTd88AUljJiW0nAlHgu/ZehZRCcYlaLToT+OtGzZ5hfbGanzceBmhlFaQpqYerV+w0rSnr+SZjFtHwITa2Bu5BshaSjmzZ13rbryod8JmqYBm4/rIu54XpBMmo=
  - secure: kert3rwfWzATIIKNYLFsR5zcdifqs1LyxCgypUnir9PpZW0Tb0Ruw7UhfgnpjTW3QHf3D5biHOCpYG4NWhpYeP5amASEYF1k+kqy2Y4FmD1EB3mCIdwQETMIvPOGdAsKcGjUA7M3efSKy1T6uGiEkE19zwkChu3ytJQ+Se63Rk0YLgFoHnF/Oa2nPnZsLO/5Py/2QAJUHA4fECBC8CMaxBxhiP/Iru0ol8gNwHvJA31LmPuFiKtNsjl0xHyfsd+rZQ6R6gwZC+Mgnq5YX1ugWKfZdCUCsuW2bhFuPahJkXS3bZOvZvypS5mMfbkNA9HV6QwEwZwCxJAMgoV2nIS99Yz/5r2MlJhPjTJxeeNrvFX3sDNj3YETHpXkbt/6ymuNs9to9B5t5w8qjSSki+xUn0Llt7qjAdWYSv2CoxKyBFlbxuzvwHnVIe7X2Jvd2i+BxtzEaUUwvaO09jvDE9IMmA8koifkd0+4Gmvj6LwgovtqFnDboIJIHOlBHe/BVpD7xj3yeMr4/V42MaXSNkfbTvO7KJjAGrUXftO2kBJdvxFJNDesxCGYEbkv1zNW/FO3bNsvb0lkktd4I4eXniarpvP7L8f7yOPsILTJF8JBVpa/G/ad8w5CvgZ7W+TNqy+xV24FP/R3cqpHBZJWSBtGbwWjBoeMwRE+RRUoJt2PuMg=
before_install:
- curl -L https://github.com/arcnmx/ci/archive/0.1.tar.gz | tar -xzC $HOME && . $HOME/ci-0.1/src
script:
- cargo test
- cargo build
deploy:
  provider: script
  script: 'true'
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"
before_deploy:
- cargo doc
- cargo package
after_deploy:
- cargo pages-publish
- cargo publish
