language: rust
rust:
- stable
- beta
- nightly
sudo: false
os:
- linux
cache:
  directories:
  - "$HOME/.cargo"
  - target
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
env:
  matrix:
  - CARGO_FEATURES=
  global:
  - secure: HKjJNlircbxNwT51F47JiAH1ruxJOA5veOlmycSod6AR6If09eIu7lQLeRnHaAcys12ccJ9sUq9Z50fPVI3Bc7PVM2cNIWnybTM0jhOLHe9hd5M1YS+4p4qlgTiWBUxVveqVmy9OXbPN8esH9VempJy1pV68YgijkaL8OnM8MPZGMEuZbYF7+5pdWTHSO/h2twXWK5SYGqTLwxM+NJMIOmRznjmi0aI0Kfp1GiHEFKMGEvaLjeaIu71rAmC6kSRohoPPfXzuJbBPx58aBSNvdl4KA8nyJtsLynjMNO0nxzzgdXnkoBXu9EuuMppu/k6rqcAKFpDX98sFU1EzXoSdPr7gWMi9T3c2Dk85kTJX+uVUxndkICQMVENFFyC5sRQFopSPsVl3xyePHJI7c/v0H/OuYvJH7K/0QOuquclZQMPBIoFXtA7cxLvv+w/6innE3ABgUE9Xt30dbRD2XkCPJfoyhmARSt0TXXl/JhCNwQWfG9LRQvshKL4mzOaEV0YjVsGXfs/IaMUrmKOA3pDyeSU8ufG8MBIUpcl17SCAFn1m8oJcRiTd88AUljJiW0nAlHgu/ZehZRCcYlaLToT+OtGzZ5hfbGanzceBmhlFaQpqYerV+w0rSnr+SZjFtHwITa2Bu5BshaSjmzZ13rbryod8JmqYBm4/rIu54XpBMmo=
  - secure: MATNUlJrAY2lLASSRAStOltO6gDdqGaGTskueBtFd70Vmiw0P0Ed94WLkwqlyARMKUr6I3LFF4XSjcDZfa7Wjyk7lioOsGBx3BL57beWXZoJi8fSaU/ewOlUbSPpTpeme1tColdm7QZa3dRowGg3Fbr7Q/QQ151wx2zQEQjl95m5J2c8RLHKm4GU4hFk0WFpYiDmIlzmwR2XG1nujB7RABOpO08AGSzMXnAxK2xjP5Mk67/ugY13Jrq0FCj6nBl1hYDgyPpkxq51lTUxgrVXJ0Vrx8NJhuBcyug6Ihp/EFuzFrbPpJ+yK8vM2AbTD7pMZxqUu6TCM2xjtbssMpmF9yIjClytJTbblwRYiuTBJXZ4tEBPjktLjQm+DfFZnEZfDk3Kg6wewq97msKgiRKCpfJWa8VqbZb7ObhomKPYpY4zpsWwzaG7ojqPbfg0/DB5wn6kwguGgY28Q3I4p3hDHAr2/tK7VHbyOOP/M+CrKnMhLqZKKNBxKXDHnKkEaxMoPQVxz/2vGRaa+rmVVh/B2Y7Y/f34w7VLDpf9pAy/rWoKlFtkKjIkDXm4GOFP1GsynFMJkVPzygJKfhJyjDuQsmBLg+J40xevSkTiRgQWPaXvhkShKaciubKajWpWg5PyTV+tt9dftSCzBieUAkwA94Rc8X5EsGmSi7V6Vpz6V98=
before_install:
- curl -L https://github.com/arcnmx/ci/archive/0.1.tar.gz | tar -xzC $HOME && . $HOME/ci-0.1/src
script:
- cargo test
- cargo build
deploy:
  provider: script
  script: 'true'
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"
before_deploy:
- cargo doc
- cargo package
after_deploy:
- cargo pages-publish
- cargo publish
